// @generated by scripts/generate-tool-routes.ts — do not edit.
// Run `pnpm routes` after changing the registry.
import { ToolShell } from "@/components/tools/tool-shell";
import { getTool } from "@/lib/tools/registry";
import { toolMetadata } from "@/lib/tools/page-metadata";
import QrGenerator from "@/components/tools/widgets/qr-generator";

export const dynamic = "force-static";

export const metadata = toolMetadata("qr-code-generator");

export default function Page() {
  return (
    <ToolShell
      tool={getTool("qr-code-generator")!}
      widget={<QrGenerator />}
    />
  );
}
