// @generated by scripts/generate-tool-routes.ts — do not edit.
// Run `pnpm routes` after changing the registry.
import { ToolShell } from "@/components/tools/tool-shell";
import { getTool } from "@/lib/tools/registry";
import { toolMetadata } from "@/lib/tools/page-metadata";
import ImageConverter from "@/components/tools/widgets/image-converter";
import { CONVERSIONS } from "@/lib/tools/image/spec";

export const dynamic = "force-static";

export const metadata = toolMetadata("image-converter");

export default function Page() {
  return (
    <ToolShell
      tool={getTool("image-converter")!}
      widget={<ImageConverter {...CONVERSIONS["image-converter"]} />}
    />
  );
}
