// @generated by scripts/generate-tool-routes.ts — do not edit.
// Run `pnpm routes` after changing the registry.
import { ToolShell } from "@/components/tools/tool-shell";
import { getTool } from "@/lib/tools/registry";
import { toolMetadata } from "@/lib/tools/page-metadata";
import ChmodCalculator from "@/components/tools/widgets/chmod-calculator";

export const dynamic = "force-static";

export const metadata = toolMetadata("chmod-calculator");

export default function Page() {
  return (
    <ToolShell
      tool={getTool("chmod-calculator")!}
      widget={<ChmodCalculator />}
    />
  );
}
