// @generated by scripts/generate-tool-routes.ts — do not edit.
// Run `pnpm routes` after changing the registry.
import { ToolShell } from "@/components/tools/tool-shell";
import { getTool } from "@/lib/tools/registry";
import { toolMetadata } from "@/lib/tools/page-metadata";
import RegexTester from "@/components/tools/widgets/regex-tester";

export const dynamic = "force-static";

export const metadata = toolMetadata("regex-tester");

export default function Page() {
  return (
    <ToolShell
      tool={getTool("regex-tester")!}
      widget={<RegexTester />}
    />
  );
}
