// @generated by scripts/generate-tool-routes.ts — do not edit.
// Run `pnpm routes` after changing the registry.
import { ToolShell } from "@/components/tools/tool-shell";
import { getTool } from "@/lib/tools/registry";
import { toolMetadata } from "@/lib/tools/page-metadata";
import TextDiff from "@/components/tools/widgets/text-diff";

export const dynamic = "force-static";

export const metadata = toolMetadata("text-diff-checker");

export default function Page() {
  return (
    <ToolShell
      tool={getTool("text-diff-checker")!}
      widget={<TextDiff />}
    />
  );
}
