// @generated by scripts/generate-tool-routes.ts — do not edit.
// Run `pnpm routes` after changing the registry.
import { ToolShell } from "@/components/tools/tool-shell";
import { getTool } from "@/lib/tools/registry";
import { toolMetadata } from "@/lib/tools/page-metadata";
import UrlEncoder from "@/components/tools/widgets/url-encoder";

export const dynamic = "force-static";

export const metadata = toolMetadata("url-encoder-decoder");

export default function Page() {
  return (
    <ToolShell
      tool={getTool("url-encoder-decoder")!}
      widget={<UrlEncoder />}
    />
  );
}
