export const metadata = {
  title: "Kavitha Kanchana - Associate Software Engineer | Startup Founder | AI/ML & Automation Specialist",
  description: "Kavitha Kanchana is an Associate Software Engineer at Xleron and Startup Founder at Ryzera Technologies, specializing in AI/ML integration, workflow automation with n8n/Make.com, and full-stack development. Expert in React, Next.js, Three.js, and cutting-edge technologies.",
  keywords: [
    "Kavitha Kanchana",
    "Associate Software Engineer",
    "Startup Founder",
    "Full-Stack Developer",
    "AI/ML Integration Specialist",
    "Automation Specialist",
    "MERN Stack Developer",
    "React Developer",
    "Next.js Developer",
    "Three.js Developer",
    "OpenAI API",
    "GPT-4 Integration",
    "n8n Automation",
    "Make.com",
    "Workflow Automation",
    "Sri Lanka Software Engineer",
    "Xleron",
    "Ryzera Technologies",
    "Birmingham City University",
    "AI-Powered Applications",
    "3D Web Development",
    "Open Source Contributor",
    "Generation ALPHA",
    "OpenMRS",
    "GSoC",
    "Upwork Automation Engineer",
    "Fiverr Web Developer"
  ],
  openGraph: {
    title: "Kavitha Kanchana - Software Engineer, Startup Founder & Automation Specialist",
    description: "Associate Software Engineer at Xleron | Startup Founder at Ryzera Technologies | AI/ML & Automation Specialist | Full-Stack Developer",
    type: "website",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "Kavitha Kanchana - Software Engineer, Startup Founder & Automation Specialist",
    description: "Associate Software Engineer at Xleron | Startup Founder at Ryzera Technologies | AI/ML & Automation Specialist",
  },
}; 