// @generated by scripts/generate-tool-routes.ts — do not edit.
// Run `pnpm routes` after changing the registry.
import { ToolShell } from "@/components/tools/tool-shell";
import { getTool } from "@/lib/tools/registry";
import { toolMetadata } from "@/lib/tools/page-metadata";
import AspectRatioCalculator from "@/components/tools/widgets/aspect-ratio-calculator";

export const dynamic = "force-static";

export const metadata = toolMetadata("aspect-ratio-calculator");

export default function Page() {
  return (
    <ToolShell
      tool={getTool("aspect-ratio-calculator")!}
      widget={<AspectRatioCalculator />}
    />
  );
}
