import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { buildableTools, publicTools } from "./registry";
import { WIDGET_COMPONENTS } from "../../../scripts/widget-components";

/**
 * Tool pages are one generated route each, not one dynamic route.
 *
 * That is what stopped every tool page shipping every widget: one dynamic route
 * is one module graph, so at 23 tools a page carried 28.6 kB of widgets to run
 * one of them. Per-route splitting took first-load JavaScript from 127 kB to
 * under 100 kB and, more usefully, stopped it growing with the catalogue.
 *
 * The cost is generated files that can fall out of step with the registry, and
 * the failure would be quiet: a tool in the registry with no route 404s while
 * still appearing in the hub, the sitemap and the JSON-LD. These tests are the
 * reason that cannot happen without the build going red.
 */

const ROOT = "src/app/(tools)/tools";
const MARKER = "@generated by scripts/generate-tool-routes.ts";

function generatedRoutes(): string[] {
  return readdirSync(ROOT, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .filter((e) => {
      const page = join(ROOT, e.name, "page.tsx");
      return existsSync(page) && readFileSync(page, "utf8").includes(MARKER);
    })
    .map((e) => e.name);
}

describe("every buildable tool has a route", () => {
  it("generates one page per tool, and no extras", () => {
    // Both directions matter. A missing route is a 404 the hub still links to;
    // a leftover route is a live page for a tool that was deleted.
    expect(generatedRoutes().sort()).toEqual(
      buildableTools().map((t) => t.slug).sort()
    );
  });

  it("has a widget mapped for every tool", () => {
    // `pnpm routes` fails loudly on a missing entry, but only if someone runs
    // it. This fails in CI whether they did or not.
    for (const tool of buildableTools()) {
      expect(WIDGET_COMPONENTS[tool.slug], `no widget for ${tool.slug}`).toBeTruthy();
    }
  });

  it("maps no widget to a slug that does not exist", () => {
    const slugs = new Set(buildableTools().map((t) => t.slug));
    for (const slug of Object.keys(WIDGET_COMPONENTS)) {
      expect(slugs.has(slug), `${slug} is mapped but not in the registry`).toBe(true);
    }
  });
});

describe("the generated routes stay generated", () => {
  it("imports exactly one widget per page", () => {
    // The whole point of the split. A page importing two widgets, or importing
    // the old slug-keyed map, puts the catalogue back in one graph.
    for (const slug of generatedRoutes()) {
      const src = readFileSync(join(ROOT, slug, "page.tsx"), "utf8");
      const widgetImports = src
        .split("\n")
        .filter((l) => l.startsWith("import") && l.includes("/widgets/"));
      expect(widgetImports, `${slug} imports ${widgetImports.length} widgets`).toHaveLength(1);
      expect(src).not.toContain("tool-widget");
    }
  });

  it("pins the slug in both the metadata and the shell", () => {
    for (const slug of generatedRoutes()) {
      const src = readFileSync(join(ROOT, slug, "page.tsx"), "utf8");
      expect(src).toContain(`toolMetadata(${JSON.stringify(slug)})`);
      expect(src).toContain(`getTool(${JSON.stringify(slug)})`);
    }
  });
});

describe("the shell cannot reach a widget on its own", () => {
  it("imports no widget and no widget map", () => {
    // This is the load-bearing constraint. The shell importing the map is what
    // made every page carry every widget, and it is a one-line regression.
    const shell = readFileSync("src/components/tools/tool-shell.tsx", "utf8");
    expect(shell).not.toContain("./tool-widget");
    expect(shell).not.toContain("/widgets/");
  });
});

describe("public tools are reachable", () => {
  it("routes every tool the hub will link to", () => {
    const routes = new Set(generatedRoutes());
    for (const tool of publicTools()) {
      expect(routes.has(tool.slug), `${tool.slug} is public but has no route`).toBe(true);
    }
  });
});
