// @generated by scripts/generate-tool-routes.ts — do not edit.
// Run `pnpm routes` after changing the registry.
import { ToolShell } from "@/components/tools/tool-shell";
import { getTool } from "@/lib/tools/registry";
import { toolMetadata } from "@/lib/tools/page-metadata";
import SubtitleConverter from "@/components/tools/widgets/subtitle-converter";

export const dynamic = "force-static";

export const metadata = toolMetadata("srt-to-vtt");

export default function Page() {
  return (
    <ToolShell
      tool={getTool("srt-to-vtt")!}
      widget={<SubtitleConverter />}
    />
  );
}
