// @generated by scripts/generate-tool-routes.ts — do not edit.
// Run `pnpm routes` after changing the registry.
import { ToolShell } from "@/components/tools/tool-shell";
import { getTool } from "@/lib/tools/registry";
import { toolMetadata } from "@/lib/tools/page-metadata";
import DataSizeConverter from "@/components/tools/widgets/data-size-converter";

export const dynamic = "force-static";

export const metadata = toolMetadata("data-size-converter");

export default function Page() {
  return (
    <ToolShell
      tool={getTool("data-size-converter")!}
      widget={<DataSizeConverter />}
    />
  );
}
