// @generated by scripts/generate-tool-routes.ts — do not edit.
// Run `pnpm routes` after changing the registry.
import { ToolShell } from "@/components/tools/tool-shell";
import { getTool } from "@/lib/tools/registry";
import { toolMetadata } from "@/lib/tools/page-metadata";
import Base64Converter from "@/components/tools/widgets/base64-converter";

export const dynamic = "force-static";

export const metadata = toolMetadata("base64-encoder-decoder");

export default function Page() {
  return (
    <ToolShell
      tool={getTool("base64-encoder-decoder")!}
      widget={<Base64Converter />}
    />
  );
}
