// @generated by scripts/generate-tool-routes.ts — do not edit.
// Run `pnpm routes` after changing the registry.
import { ToolShell } from "@/components/tools/tool-shell";
import { getTool } from "@/lib/tools/registry";
import { toolMetadata } from "@/lib/tools/page-metadata";
import EntityConverter from "@/components/tools/widgets/entity-converter";

export const dynamic = "force-static";

export const metadata = toolMetadata("html-entity-converter");

export default function Page() {
  return (
    <ToolShell
      tool={getTool("html-entity-converter")!}
      widget={<EntityConverter />}
    />
  );
}
