/**
 * Emits one route directory per buildable tool.
 *
 * Tool pages used to be a single `[slug]` route. Every page then shipped every
 * widget, because one dynamic route is one module graph, and the cost grew with
 * the catalogue: at 23 tools that was 28.6 kB of widgets on a page that runs
 * one of them. One route per tool ships one widget. Measured on the same build,
 * first-load JavaScript went from 127 kB to 99.4 kB, and it now stays there
 * whether the catalogue holds twenty tools or thirty.
 *
 * The files are generated rather than hand-written so they cannot drift from
 * the registry, and `src/lib/tools/routes.test.ts` fails the build if they do.
 * Run after adding a tool:
 *
 *     pnpm routes
 */
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import { buildableTools } from "../src/lib/tools/registry";
import { WIDGET_COMPONENTS } from "./widget-components";

const ROOT = "src/app/(tools)/tools";
const MARKER = "@generated by scripts/generate-tool-routes.ts";

// Remove previously generated routes first, so a tool deleted from the registry
// does not leave a live page behind. Only directories carrying the marker are
// touched; `category` and anything hand-written are left alone.
for (const entry of readdirSync(ROOT, { withFileTypes: true })) {
  if (!entry.isDirectory()) continue;
  const page = join(ROOT, entry.name, "page.tsx");
  if (existsSync(page) && readFileSync(page, "utf8").includes(MARKER)) {
    rmSync(join(ROOT, entry.name), { recursive: true });
  }
}

let written = 0;
for (const tool of buildableTools()) {
  const component = WIDGET_COMPONENTS[tool.slug];
  if (!component) {
    console.error(`  no widget mapped for ${tool.slug} — add it to scripts/widget-components.ts`);
    process.exitCode = 1;
    continue;
  }

  const dir = join(ROOT, tool.slug);
  mkdirSync(dir, { recursive: true });
  writeFileSync(
    join(dir, "page.tsx"),
    `// ${MARKER} — do not edit.
// Run \`pnpm routes\` after changing the registry.
import { ToolShell } from "@/components/tools/tool-shell";
import { getTool } from "@/lib/tools/registry";
import { toolMetadata } from "@/lib/tools/page-metadata";
import ${component.name} from "${component.from}";${component.extraImport ? `\n${component.extraImport}` : ""}

export const dynamic = "force-static";

export const metadata = toolMetadata(${JSON.stringify(tool.slug)});

export default function Page() {
  return (
    <ToolShell
      tool={getTool(${JSON.stringify(tool.slug)})!}
      widget={<${component.name} ${component.props ?? ""}/>}
    />
  );
}
`
  );
  written += 1;
}

console.log(`generated ${written} tool routes`);
