// @generated by scripts/generate-tool-routes.ts — do not edit.
// Run `pnpm routes` after changing the registry.
import { ToolShell } from "@/components/tools/tool-shell";
import { getTool } from "@/lib/tools/registry";
import { toolMetadata } from "@/lib/tools/page-metadata";
import CsvJsonConverter from "@/components/tools/widgets/csv-json-converter";

export const dynamic = "force-static";

export const metadata = toolMetadata("csv-to-json-converter");

export default function Page() {
  return (
    <ToolShell
      tool={getTool("csv-to-json-converter")!}
      widget={<CsvJsonConverter />}
    />
  );
}
