// @generated by scripts/generate-tool-routes.ts — do not edit.
// Run `pnpm routes` after changing the registry.
import { ToolShell } from "@/components/tools/tool-shell";
import { getTool } from "@/lib/tools/registry";
import { toolMetadata } from "@/lib/tools/page-metadata";
import PdfToText from "@/components/tools/widgets/pdf-to-text";

export const dynamic = "force-static";

export const metadata = toolMetadata("pdf-to-text");

export default function Page() {
  return (
    <ToolShell
      tool={getTool("pdf-to-text")!}
      widget={<PdfToText />}
    />
  );
}
