// @generated by scripts/generate-tool-routes.ts — do not edit.
// Run `pnpm routes` after changing the registry.
import { ToolShell } from "@/components/tools/tool-shell";
import { getTool } from "@/lib/tools/registry";
import { toolMetadata } from "@/lib/tools/page-metadata";
import WordCounter from "@/components/tools/widgets/word-counter";

export const dynamic = "force-static";

export const metadata = toolMetadata("word-counter");

export default function Page() {
  return (
    <ToolShell
      tool={getTool("word-counter")!}
      widget={<WordCounter />}
    />
  );
}
