// @generated by scripts/generate-tool-routes.ts — do not edit.
// Run `pnpm routes` after changing the registry.
import { ToolShell } from "@/components/tools/tool-shell";
import { getTool } from "@/lib/tools/registry";
import { toolMetadata } from "@/lib/tools/page-metadata";
import ImageResizer from "@/components/tools/widgets/image-resizer";

export const dynamic = "force-static";

export const metadata = toolMetadata("image-resizer");

export default function Page() {
  return (
    <ToolShell
      tool={getTool("image-resizer")!}
      widget={<ImageResizer />}
    />
  );
}
