// @generated by scripts/generate-tool-routes.ts — do not edit.
// Run `pnpm routes` after changing the registry.
import { ToolShell } from "@/components/tools/tool-shell";
import { getTool } from "@/lib/tools/registry";
import { toolMetadata } from "@/lib/tools/page-metadata";
import UuidGenerator from "@/components/tools/widgets/uuid-generator";

export const dynamic = "force-static";

export const metadata = toolMetadata("uuid-generator");

export default function Page() {
  return (
    <ToolShell
      tool={getTool("uuid-generator")!}
      widget={<UuidGenerator />}
    />
  );
}
